set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER_TARGET arm-none-eabi)

set(TOOLCHAIN arm-none-eabi_14.2.rel1-1)

file(GLOB TOOLCHAIN_CANDIDATES
	 LIST_DIRECTORIES true
	 CONFIGURE_DEPENDS
	 "/opt/arm-gnu-toolchain-*-${CMAKE_C_COMPILER_TARGET}/bin"
	 "/Applications/ArmGNUToolchain/*/${CMAKE_C_COMPILER_TARGET}/bin"
	 "C:/Program Files*/Arm GNU Toolchain ${CMAKE_C_COMPILER_TARGET}/*/bin"
)

if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.18")
	set(TOOLCHAIN_ORDER NATURAL)
else()
	set(TOOLCHAIN_ORDER STRING)
endif()

list(SORT TOOLCHAIN_CANDIDATES COMPARE ${TOOLCHAIN_ORDER} ORDER DESCENDING)

find_program(CMAKE_C_COMPILER
	NAMES ${CMAKE_C_COMPILER_TARGET}-gcc ${CMAKE_C_COMPILER_TARGET}-gcc.exe
	HINTS
		ENV TOOLCHAIN_BIN_DIR
		"$ENV{HOME}/${TOOLCHAIN}/bin"
		"/opt/${TOOLCHAIN}/bin"
		"/srv/${TOOLCHAIN}/bin"
		"/usr/local/${TOOLCHAIN}/bin"
		"/opt/homebrew/bin"
		"C:/Program Files (x86)/Arm GNU Toolchain ${CMAKE_C_COMPILER_TARGET}/14.2 rel1/bin"
		${TOOLCHAIN_CANDIDATES}
	DOC "Path to the ARM toolchain compiler"
)

if(NOT CMAKE_C_COMPILER)
	message(FATAL_ERROR "Could not find '${CMAKE_C_COMPILER_TARGET}' toolchain binaries. Please set TOOLCHAIN_BIN_DIR or add it to your system PATH.")
endif()

get_filename_component(TOOLCHAIN_BIN_DIR "${CMAKE_C_COMPILER}" DIRECTORY)

if(WIN32)
	set(TOOLCHAIN_EXE_SUFFIX .exe)
else()
	set(TOOLCHAIN_EXE_SUFFIX "")
endif()

set(CMAKE_ASM_COMPILER "${TOOLCHAIN_BIN_DIR}/${CMAKE_C_COMPILER_TARGET}-gcc${TOOLCHAIN_EXE_SUFFIX}")
set(CMAKE_AR "${TOOLCHAIN_BIN_DIR}/${CMAKE_C_COMPILER_TARGET}-gcc-ar${TOOLCHAIN_EXE_SUFFIX}")
set(CMAKE_RANLIB "${TOOLCHAIN_BIN_DIR}/${CMAKE_C_COMPILER_TARGET}-gcc-ranlib${TOOLCHAIN_EXE_SUFFIX}")
set(CMAKE_LINKER "${TOOLCHAIN_BIN_DIR}/${CMAKE_C_COMPILER_TARGET}-gcc${TOOLCHAIN_EXE_SUFFIX}")
set(CMAKE_OBJCOPY "${TOOLCHAIN_BIN_DIR}/${CMAKE_C_COMPILER_TARGET}-objcopy${TOOLCHAIN_EXE_SUFFIX}")
set(CMAKE_SIZE "${TOOLCHAIN_BIN_DIR}/${CMAKE_C_COMPILER_TARGET}-size${TOOLCHAIN_EXE_SUFFIX}")

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_ASM_COMPILER_WORKS 1)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
